// Configuration constants
const CONFIG = {
  // Animation settings
  ANIMATION_DURATION: 3000,
  DRAG_SENSITIVITY: 1.5,

  // Hold behavior settings
  HOLD_DELAY: 150, // Milliseconds to wait before hold is detected
  HOLD_DURATION: 3000, // Total duration to reach maximum angle (ms)
  HOLD_INTERVAL: 10, // How often to update during hold (ms)
  HOLD_RELEASE_DURATION: 3000, // Duration to reset angle after hold release (ms)
  HOLD_INITIAL_PROGRESS: 0.08, // Initial progress bump for instant visual feedback on press

  // Visual settings
  BLOCK_WIDTH: 235,
  COLLAPSED_HEIGHT: 30,
  DY: 40,
  X_OFFSET: 30,
  Y_OFFSET: 10,
  GAP_MIDDLE: 200,
  LEG_ANGLE_DEG: 50,
  DIST_BETWEEN_SUBS: 35,
  /** Max subs visible in a block before showing scroll; rest are scrollable */
  MAX_BLOCK_SUBS_VISIBLE: 8,
  /** Height of each expandable container-group header */
  CONTAINER_HEADER_HEIGHT: 22,
  /** Marquee for long sub-labels: min name length to enable, clip width (px), scroll offset (px), duration */
  MARQUEE_LABEL_MIN_LEN: 24,
  MARQUEE_CLIP_W: 156,
  MARQUEE_OFFSET: 230,
  MARQUEE_DUR: "6s",
  /** Extra space (px) below the last sub in each container-group-content before the next container */
  CONTAINER_CONTENT_END_GAP: 10,
  /** Reset button icon (block and container reset) */
  RESET_ICON: "↺",

  // Colors
  COLORS: {
    BLOCK_FILL: "#e8f5e9 ",
    BLOCK_HIGHLIGHT: "#ffffff", // d1c4e9
    MODIFIED_BLOCK: "#c8e6c9",
    SKIP_LINE: "#ff7f0e",
    SKIP_LINE_HIGHLIGHT: "#0016ff",
  },

  // Server settings
  FILES_SERVER_URL: "https://bendingocean.sfo3.cdn.digitaloceanspaces.com",

  /** When true, interactive UI checks experiment cache before queueing generation (uses batch from session_id) */
  USE_EXPERIMENT_CACHE: true,

  // Image generation servers
  COMFY_GENERATION_SERVER_URL: "http://127.0.0.1:8188",
  GENERATION_SERVER_URL: "http://localhost:8000",

  // ViewComfy remote inference (optional). Set your own credentials; do not commit secrets.
  VIEWCOMFY_API_URL: "",
  VIEWCOMFY_CLIENT_ID: "",
  VIEWCOMFY_CLIENT_SECRET: "",

  /** Tableau 10 categorical colors (hex) for legend / blockTypeCategories */
  TABLEAU10: [
    "#4e79a7", "#f28e2b", "#e15759", "#76b7b2", "#59a14f",
    "#edc948", "#b07aa1", "#ff9da7", "#9c755f", "#bab0ac",
  ],

  /** Container highlight colors (left accent per sub) */
  CONTAINER_COLORS: {
    SpatialTransformer: "#e377c2",
    Upsample: "#2ca02c",
    Downsample: "#d62728",
    ResBlock: "#1f77b4",
    TimestepEmbedSequential: "#9467bd",
    CrossAttention: "#ff7f0e",
    Other: "#999",
    Sequential: "#76b7b2",
  },

  BENDABLE: ["unet"],
  // Unclickable elements
  UNBENDABLE: [
    "clip",
    "latents",
    "text_conditioned_latents",
    "scheduler",
    "text_embeddings",
    "latent_seed_noise",
    "variational_autoencoder_vae",
  ],

  // Rotation angles (legacy)
  ANGLES: [0, 90, 180, 270],

  /** Bending operation types: symbol, levels, default, module_args key */
  BENDING_TYPES: {
    add_noise: {
      symbol: "⊕",
      label: "Add Noise",
      defaultValue: 0,
      levels: [0, 1, 2],
      module_args_key: "noise_std",
    },
    multiply: {
      symbol: "×",
      label: "Multiply",
      defaultValue: 1,
      levels: [0, 0.5, 1, 1.5, 2],
      module_args_key: "scalar",
    },
    rotate: {
      symbol: "↻",
      label: "Rotate",
      defaultValue: 0,
      levels: [0, 90, 180, 270],
      module_args_key: "angle_degrees",
    },
  },

  // Experiments
  EXPERIMENTS: {
    UNet_Rotation_Orb: "A floating orb",
    UNet_Rotation_Person: "Analog style portrait of a person",
    UNet_Rotation_Mountain:
      "beautiful mountain landscape, lake, snow, oil painting 8 k hd",
  },
};

// UNet block definitions
const UNET_BLOCKS = {
  SDTurbo: {
    //Comfy model
    blocks: [
      "input_blocks.0.0",
      "input_blocks.1.0.in_layers.2",
      "input_blocks.1.0.out_layers.3",
      "input_blocks.2.0.in_layers.2",
      "input_blocks.2.0.out_layers.3",
      "input_blocks.3.0.op",
      "input_blocks.4.0.in_layers.2",
      "input_blocks.4.0.out_layers.3",
      "input_blocks.4.0.skip_connection",
      "input_blocks.5.0.in_layers.2",
      "input_blocks.5.0.out_layers.3",
      "input_blocks.6.0.op",
      "input_blocks.7.0.in_layers.2",
      "input_blocks.7.0.out_layers.3",
      "input_blocks.7.0.skip_connection",
      "input_blocks.8.0.in_layers.2",
      "input_blocks.8.0.out_layers.3",
      "middle_block.0.in_layers.2",
      "middle_block.0.out_layers.3",
      "middle_block.2.in_layers.2",
      "middle_block.2.out_layers.3",
      "output_blocks.0.0.in_layers.2",
      "output_blocks.0.0.out_layers.3",
      "output_blocks.0.0.skip_connection",
      "output_blocks.1.0.in_layers.2",
      "output_blocks.1.0.out_layers.3",
      "output_blocks.1.0.skip_connection",
      "output_blocks.2.0.in_layers.2",
      "output_blocks.2.0.out_layers.3",
      "output_blocks.2.0.skip_connection",
      "output_blocks.2.2.conv",
      "output_blocks.3.0.in_layers.2",
      "output_blocks.3.0.out_layers.3",
      "output_blocks.3.0.skip_connection",
      "output_blocks.4.0.in_layers.2",
      "output_blocks.4.0.out_layers.3",
      "output_blocks.4.0.skip_connection",
      "output_blocks.5.0.in_layers.2",
      "output_blocks.5.0.out_layers.3",
      "output_blocks.5.0.skip_connection",
      "output_blocks.5.2.conv",
      "output_blocks.6.0.in_layers.2",
      "output_blocks.6.0.out_layers.3",
      "output_blocks.6.0.skip_connection",
      "output_blocks.7.0.in_layers.2",
      "output_blocks.7.0.out_layers.3",
      "output_blocks.7.0.skip_connection",
      "output_blocks.8.0.in_layers.2",
      "output_blocks.8.0.out_layers.3",
      "output_blocks.8.0.skip_connection",
      "out.2",
    ],
    blockTypes: [
      "UNetModel.ModuleList.TimestepEmbedSequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.Downsample.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.Downsample.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.Upsample.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.Upsample.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "UNetModel.ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "UNetModel.Sequential.Conv2d",
    ],
    blockTypeCategories: {
      Conv2d: "#666666",
      "ResBlock.Sequential.Conv2d": "#1f77b4",
      "ResBlock.Conv2d": "#ff7f0e", // skip-connection
      "SpatialTransformer.Conv2d": "#e377c2",
      "Upsample.Conv2d": "#2ca02c",
      "Downsample.Conv2d": "#d62728",
    },
  },
  "SD1.4": {
    //Comfy model
    blocks: [
      "input_blocks.0.0",
      "input_blocks.1.0.in_layers.2",
      "input_blocks.1.0.out_layers.3",
      "input_blocks.1.1.proj_in",
      "input_blocks.1.1.proj_out",
      "input_blocks.2.0.in_layers.2",
      "input_blocks.2.0.out_layers.3",
      "input_blocks.2.1.proj_in",
      "input_blocks.2.1.proj_out",
      "input_blocks.3.0.op",
      "input_blocks.4.0.in_layers.2",
      "input_blocks.4.0.out_layers.3",
      "input_blocks.4.0.skip_connection",
      "input_blocks.4.1.proj_in",
      "input_blocks.4.1.proj_out",
      "input_blocks.5.0.in_layers.2",
      "input_blocks.5.0.out_layers.3",
      "input_blocks.5.1.proj_in",
      "input_blocks.5.1.proj_out",
      "input_blocks.6.0.op",
      "input_blocks.7.0.in_layers.2",
      "input_blocks.7.0.out_layers.3",
      "input_blocks.7.0.skip_connection",
      "input_blocks.7.1.proj_in",
      "input_blocks.7.1.proj_out",
      "input_blocks.8.0.in_layers.2",
      "input_blocks.8.0.out_layers.3",
      "input_blocks.8.1.proj_in",
      "input_blocks.8.1.proj_out",
      "input_blocks.9.0.op",
      "input_blocks.10.0.in_layers.2",
      "input_blocks.10.0.out_layers.3",
      "input_blocks.11.0.in_layers.2",
      "input_blocks.11.0.out_layers.3",
      "middle_block.0.in_layers.2",
      "middle_block.0.out_layers.3",
      "middle_block.1.proj_in",
      "middle_block.1.proj_out",
      "middle_block.2.in_layers.2",
      "middle_block.2.out_layers.3",
      "output_blocks.0.0.in_layers.2",
      "output_blocks.0.0.out_layers.3",
      "output_blocks.0.0.skip_connection",
      "output_blocks.1.0.in_layers.2",
      "output_blocks.1.0.out_layers.3",
      "output_blocks.1.0.skip_connection",
      "output_blocks.2.0.in_layers.2",
      "output_blocks.2.0.out_layers.3",
      "output_blocks.2.0.skip_connection",
      "output_blocks.2.1.conv",
      "output_blocks.3.0.in_layers.2",
      "output_blocks.3.0.out_layers.3",
      "output_blocks.3.0.skip_connection",
      "output_blocks.3.1.proj_in",
      "output_blocks.3.1.proj_out",
      "output_blocks.4.0.in_layers.2",
      "output_blocks.4.0.out_layers.3",
      "output_blocks.4.0.skip_connection",
      "output_blocks.4.1.proj_in",
      "output_blocks.4.1.proj_out",
      "output_blocks.5.0.in_layers.2",
      "output_blocks.5.0.out_layers.3",
      "output_blocks.5.0.skip_connection",
      "output_blocks.5.1.proj_in",
      "output_blocks.5.1.proj_out",
      "output_blocks.5.2.conv",
      "output_blocks.6.0.in_layers.2",
      "output_blocks.6.0.out_layers.3",
      "output_blocks.6.0.skip_connection",
      "output_blocks.6.1.proj_in",
      "output_blocks.6.1.proj_out",
      "output_blocks.7.0.in_layers.2",
      "output_blocks.7.0.out_layers.3",
      "output_blocks.7.0.skip_connection",
      "output_blocks.7.1.proj_in",
      "output_blocks.7.1.proj_out",
      "output_blocks.8.0.in_layers.2",
      "output_blocks.8.0.out_layers.3",
      "output_blocks.8.0.skip_connection",
      "output_blocks.8.1.proj_in",
      "output_blocks.8.1.proj_out",
      "output_blocks.8.2.conv",
      "output_blocks.9.0.in_layers.2",
      "output_blocks.9.0.out_layers.3",
      "output_blocks.9.0.skip_connection",
      "output_blocks.9.1.proj_in",
      "output_blocks.9.1.proj_out",
      "output_blocks.10.0.in_layers.2",
      "output_blocks.10.0.out_layers.3",
      "output_blocks.10.0.skip_connection",
      "output_blocks.10.1.proj_in",
      "output_blocks.10.1.proj_out",
      "output_blocks.11.0.in_layers.2",
      "output_blocks.11.0.out_layers.3",
      "output_blocks.11.0.skip_connection",
      "output_blocks.11.1.proj_in",
      "output_blocks.11.1.proj_out",
    ],

    // colors from d3.schemeCategory10
    // ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf"]

    blockTypeCategories: {
      Conv2d: "#666666",
      "ResBlock.Sequential.Conv2d": "#1f77b4",
      "ResBlock.Conv2d": "#ff7f0e", // skip-connection
      "SpatialTransformer.Conv2d": "#e377c2",
      "Upsample.Conv2d": "#2ca02c",
      "Downsample.Conv2d": "#d62728",
    },
    blockTypes: [
      "ModuleList.TimestepEmbedSequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.Downsample.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.Downsample.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.Downsample.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.Upsample.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.Upsample.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.Upsample.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Sequential.Conv2d",
      "ModuleList.TimestepEmbedSequential.ResBlock.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
      "ModuleList.TimestepEmbedSequential.SpatialTransformer.Conv2d",
    ],
  },
  "SD-1.4": {
    blocks: [
      "conv_in",
      "down_blocks.0.attentions.0.proj_in",
      "down_blocks.0.attentions.0.proj_out",
      "down_blocks.0.attentions.1.proj_in",
      "down_blocks.0.attentions.1.proj_out",
      "down_blocks.0.resnets.0.conv1",
      "down_blocks.0.resnets.0.conv2",
      "down_blocks.0.resnets.1.conv1",
      "down_blocks.0.resnets.1.conv2",
      "down_blocks.0.downsamplers.0.conv",
      "down_blocks.1.attentions.0.proj_in",
      "down_blocks.1.attentions.0.proj_out",
      "down_blocks.1.attentions.1.proj_in",
      "down_blocks.1.attentions.1.proj_out",
      "down_blocks.1.resnets.0.conv1",
      "down_blocks.1.resnets.0.conv2",
      "down_blocks.1.resnets.0.conv_shortcut",
      "down_blocks.1.resnets.1.conv1",
      "down_blocks.1.resnets.1.conv2",
      "down_blocks.1.downsamplers.0.conv",
      "down_blocks.2.attentions.0.proj_in",
      "down_blocks.2.attentions.0.proj_out",
      "down_blocks.2.attentions.1.proj_in",
      "down_blocks.2.attentions.1.proj_out",
      "down_blocks.2.resnets.0.conv1",
      "down_blocks.2.resnets.0.conv2",
      "down_blocks.2.resnets.0.conv_shortcut",
      "down_blocks.2.resnets.1.conv1",
      "down_blocks.2.resnets.1.conv2",
      "down_blocks.2.downsamplers.0.conv",
      "down_blocks.3.resnets.0.conv1",
      "down_blocks.3.resnets.0.conv2",
      "down_blocks.3.resnets.1.conv1",
      "down_blocks.3.resnets.1.conv2",
      "up_blocks.0.resnets.0.conv1",
      "up_blocks.0.resnets.0.conv2",
      "up_blocks.0.resnets.0.conv_shortcut",
      "up_blocks.0.resnets.1.conv1",
      "up_blocks.0.resnets.1.conv2",
      "up_blocks.0.resnets.1.conv_shortcut",
      "up_blocks.0.resnets.2.conv1",
      "up_blocks.0.resnets.2.conv2",
      "up_blocks.0.resnets.2.conv_shortcut",
      "up_blocks.0.upsamplers.0.conv",
      "up_blocks.1.attentions.0.proj_in",
      "up_blocks.1.attentions.0.proj_out",
      "up_blocks.1.attentions.1.proj_in",
      "up_blocks.1.attentions.1.proj_out",
      "up_blocks.1.attentions.2.proj_in",
      "up_blocks.1.attentions.2.proj_out",
      "up_blocks.1.resnets.0.conv1",
      "up_blocks.1.resnets.0.conv2",
      "up_blocks.1.resnets.0.conv_shortcut",
      "up_blocks.1.resnets.1.conv1",
      "up_blocks.1.resnets.1.conv2",
      "up_blocks.1.resnets.1.conv_shortcut",
      "up_blocks.1.resnets.2.conv1",
      "up_blocks.1.resnets.2.conv2",
      "up_blocks.1.resnets.2.conv_shortcut",
      "up_blocks.1.upsamplers.0.conv",
      "up_blocks.2.attentions.0.proj_in",
      "up_blocks.2.attentions.0.proj_out",
      "up_blocks.2.attentions.1.proj_in",
      "up_blocks.2.attentions.1.proj_out",
      "up_blocks.2.attentions.2.proj_in",
      "up_blocks.2.attentions.2.proj_out",
      "up_blocks.2.resnets.0.conv1",
      "up_blocks.2.resnets.0.conv2",
      "up_blocks.2.resnets.0.conv_shortcut",
      "up_blocks.2.resnets.1.conv1",
      "up_blocks.2.resnets.1.conv2",
      "up_blocks.2.resnets.1.conv_shortcut",
      "up_blocks.2.resnets.2.conv1",
      "up_blocks.2.resnets.2.conv2",
      "up_blocks.2.resnets.2.conv_shortcut",
      "up_blocks.2.upsamplers.0.conv",
      "up_blocks.3.attentions.0.proj_in",
      "up_blocks.3.attentions.0.proj_out",
      "up_blocks.3.attentions.1.proj_in",
      "up_blocks.3.attentions.1.proj_out",
      "up_blocks.3.attentions.2.proj_in",
      "up_blocks.3.attentions.2.proj_out",
      "up_blocks.3.resnets.0.conv1",
      "up_blocks.3.resnets.0.conv2",
      "up_blocks.3.resnets.0.conv_shortcut",
      "up_blocks.3.resnets.1.conv1",
      "up_blocks.3.resnets.1.conv2",
      "up_blocks.3.resnets.1.conv_shortcut",
      "up_blocks.3.resnets.2.conv1",
      "up_blocks.3.resnets.2.conv2",
      "up_blocks.3.resnets.2.conv_shortcut",
      "mid_block.attentions.0.proj_in",
      "mid_block.attentions.0.proj_out",
      "mid_block.resnets.0.conv1",
      "mid_block.resnets.0.conv2",
      "mid_block.resnets.1.conv1",
      "mid_block.resnets.1.conv2",
      "conv_out",
    ],
    blockTypes: [
      "Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Downsample2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Downsample2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Downsample2D.Conv2d",
      "ModuleList.DownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.DownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.DownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.DownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.Upsample2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Upsample2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Upsample2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Transformer2DModel.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "UNetMidBlock2DCrossAttn.ModuleList.Transformer2DModel.Conv2d",
      "UNetMidBlock2DCrossAttn.ModuleList.Transformer2DModel.Conv2d",
      "UNetMidBlock2DCrossAttn.ModuleList.ResnetBlock2D.Conv2d",
      "UNetMidBlock2DCrossAttn.ModuleList.ResnetBlock2D.Conv2d",
      "UNetMidBlock2DCrossAttn.ModuleList.ResnetBlock2D.Conv2d",
      "UNetMidBlock2DCrossAttn.ModuleList.ResnetBlock2D.Conv2d",
      "Conv2d",
    ],
    blockTypeCategories: {
      Conv2d: "#666666",
      "Transformer2DModel.Conv2d": "#1f77b4",
      "ResnetBlock2D.Conv2d": "#ff7f0e", // skip-connection
      "SpatialTransformer.Conv2d": "#e377c2",
      "Upsample2D.Conv2d": "#2ca02c",
      "Downsample2D.Conv2d": "#d62728",
    },
  },
  "SD-turbo": {
    blocks: [
      "conv_in",
      "down_blocks.0.resnets.0.conv1",
      "down_blocks.0.resnets.0.conv2",
      "down_blocks.0.resnets.1.conv1",
      "down_blocks.0.resnets.1.conv2",
      "down_blocks.0.downsamplers.0.conv",
      "down_blocks.1.resnets.0.conv1",
      "down_blocks.1.resnets.0.conv2",
      "down_blocks.1.resnets.0.conv_shortcut",
      "down_blocks.1.resnets.1.conv1",
      "down_blocks.1.resnets.1.conv2",
      "down_blocks.1.downsamplers.0.conv",
      "down_blocks.2.resnets.0.conv1",
      "down_blocks.2.resnets.0.conv2",
      "down_blocks.2.resnets.0.conv_shortcut",
      "down_blocks.2.resnets.1.conv1",
      "down_blocks.2.resnets.1.conv2",
      "up_blocks.0.resnets.0.conv1",
      "up_blocks.0.resnets.0.conv2",
      "up_blocks.0.resnets.0.conv_shortcut",
      "up_blocks.0.resnets.1.conv1",
      "up_blocks.0.resnets.1.conv2",
      "up_blocks.0.resnets.1.conv_shortcut",
      "up_blocks.0.resnets.2.conv1",
      "up_blocks.0.resnets.2.conv2",
      "up_blocks.0.resnets.2.conv_shortcut",
      "up_blocks.0.upsamplers.0.conv",
      "up_blocks.1.resnets.0.conv1",
      "up_blocks.1.resnets.0.conv2",
      "up_blocks.1.resnets.0.conv_shortcut",
      "up_blocks.1.resnets.1.conv1",
      "up_blocks.1.resnets.1.conv2",
      "up_blocks.1.resnets.1.conv_shortcut",
      "up_blocks.1.resnets.2.conv1",
      "up_blocks.1.resnets.2.conv2",
      "up_blocks.1.resnets.2.conv_shortcut",
      "up_blocks.1.upsamplers.0.conv",
      "up_blocks.2.resnets.0.conv1",
      "up_blocks.2.resnets.0.conv2",
      "up_blocks.2.resnets.0.conv_shortcut",
      "up_blocks.2.resnets.1.conv1",
      "up_blocks.2.resnets.1.conv2",
      "up_blocks.2.resnets.1.conv_shortcut",
      "up_blocks.2.resnets.2.conv1",
      "up_blocks.2.resnets.2.conv2",
      "up_blocks.2.resnets.2.conv_shortcut",
      "mid_block.resnets.0.conv1",
      "mid_block.resnets.0.conv2",
      "mid_block.resnets.1.conv1",
      "mid_block.resnets.1.conv2",
      "conv_out",
    ],
    blockTypes: [
      "Conv2d",
      "ModuleList.DownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.DownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.DownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.DownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.DownBlock2D.ModuleList.Downsample2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.Downsample2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnDownBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Upsample2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.CrossAttnUpBlock2D.ModuleList.Upsample2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "ModuleList.UpBlock2D.ModuleList.ResnetBlock2D.Conv2d",
      "UNetMidBlock2DCrossAttn.ModuleList.ResnetBlock2D.Conv2d",
      "UNetMidBlock2DCrossAttn.ModuleList.ResnetBlock2D.Conv2d",
      "UNetMidBlock2DCrossAttn.ModuleList.ResnetBlock2D.Conv2d",
      "UNetMidBlock2DCrossAttn.ModuleList.ResnetBlock2D.Conv2d",
      "Conv2d",
    ],
    blockTypeCategories: {
      Conv2d: "#666666",
      "Transformer2DModel.Conv2d": "#1f77b4",
      "ResnetBlock2D.Conv2d": "#ff7f0e", // skip-connection
      "SpatialTransformer.Conv2d": "#e377c2",
      "Upsample2D.Conv2d": "#2ca02c",
      "Downsample2D.Conv2d": "#d62728",
    },
  },
};
